# Using mcr debian.
# Was unable to connect to ssh agent with Golang base image 😟.
# TODO Try correct that in the future.
FROM mcr.microsoft.com/devcontainers/base:debian

WORKDIR /app

COPY main.go /app
